# Generated by Django 4.1.2 on 2022-11-04 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StylistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('avatar', models.ImageField(null=True, upload_to='profiles/')),
                ('first_name', models.CharField(max_length=225, null=True)),
                ('last_name', models.CharField(max_length=225, null=True)),
                ('license', models.CharField(max_length=225, null=True)),
                ('contact', models.CharField(max_length=225, null=True)),
                ('business', models.CharField(max_length=225, null=True)),
                ('location', models.CharField(max_length=225, null=True)),
                ('specialties', models.CharField(max_length=225, null=True)),
                ('bio', models.TextField(null=True)),
                ('email', models.EmailField(max_length=225, null=True)),
                ('instagram', models.CharField(blank=True, max_length=225, null=True)),
                ('facebook', models.CharField(blank=True, max_length=225, null=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
