# Generated by Django 4.1.2 on 2022-11-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_stylistprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='avatar',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profiles/'),
        ),
    ]
